#!/usr/bin/env python3
"""Convert Linux console fonts (.psf/.psfu, optionally gzipped) into a C file
holding the printable ASCII glyphs (32..126) as 1-bit-per-pixel bitmaps.

usage: psf2c.py out.c name=font.psfu.gz [name=font.psfu.gz ...]
"""
import gzip
import struct
import sys


def load(path):
    raw = open(path, "rb").read()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)

    if raw[:2] == b"\x36\x04":  # PSF1
        mode, height = raw[2], raw[3]
        count, width, hdr = (512 if mode & 1 else 256), 8, 4
        size = height
        table = raw[hdr + count * size:] if mode & 2 else None
        mapping = {}
        if table:
            glyph, seq = 0, False
            for (v,) in struct.iter_unpack("<H", table[: len(table) // 2 * 2]):
                if v == 0xFFFF:
                    glyph, seq = glyph + 1, False
                elif v == 0xFFFE:
                    seq = True
                elif not seq:
                    mapping.setdefault(v, glyph)
    elif raw[:4] == b"\x72\xb5\x4a\x86":  # PSF2
        _, hdr, flags, count, size, height, width = struct.unpack("<7I", raw[4:32])
        table = raw[hdr + count * size:] if flags & 1 else None
        mapping = {}
        if table:
            for glyph, entry in enumerate(table.split(b"\xff")[:count]):
                for ch in entry.split(b"\xfe")[0].decode("utf-8", "replace"):
                    mapping.setdefault(ord(ch), glyph)
    else:
        sys.exit(f"{path}: not a PSF font")

    glyphs = []
    for code in range(32, 127):
        g = mapping.get(code, code) if mapping else code
        glyphs.append(raw[hdr + g * size: hdr + (g + 1) * size])
    return width, height, glyphs


out = ['/* Generated by tools/psf2c.py - do not edit. */', '#include "font.h"', ""]
for arg in sys.argv[2:]:
    name, path = arg.split("=", 1)
    width, height, glyphs = load(path)
    out.append(f"/* {path.rsplit('/', 1)[-1]} */")
    out.append(f"static const uint8_t {name}_data[] = {{")
    for code, g in zip(range(32, 127), glyphs):
        out.append("    " + "".join(f"0x{b:02x}," for b in g) + f" /* {chr(code)!r} */")
    out.append("};")
    out.append(f"const font_t {name} = {{ {width}, {height}, {name}_data }};")
    out.append("")
open(sys.argv[1], "w").write("\n".join(out))
